# Generated by Django 5.0.6 on 2024-06-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_managergroup_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('views', models.IntegerField(default=0)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
