# Generated by Django 5.0.6 on 2024-06-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-sent_date'], 'permissions': [('custom_view_newsletter', 'Может просматривать любой новостной бюллетень'), ('view_users', 'Может просматривать список пользователей сервиса'), ('block_users', 'Может заблокировать пользователей сервиса'), ('disable_newsletter', 'Может отключить новостные бюллетени')]},
        ),
    ]
